[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "acme.server"
version = "0.0.1"
description = ""

[tool.hatch.build.targets.sdist.force-include]
"../src/acme/server" = "src/acme/server"

[tool.hatch.build.targets.wheel]
packages = ["src/acme"]
